version: '3.8'

services:

  django:
    container_name: django
    depends_on : 
      - pgdb
    build:
      context: ./transcendance
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transcendance:/usr/src/app/
    ports:
      - 8000:8000
    env_file: ./.env

  pgdb:
    image: postgres
    container_name: pgdb
    build:
      context: ./postgres
    env_file: ./.env
